<?php
function getValidCountries() {
    return [
        'Afganistán', 'Albania', 'Alemania', 'Andorra', 'Angola', 'Anguila', 'Antártida', 'Antigua y Barbuda',
        'Arabia Saudí', 'Argelia', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaiyán',
        'Bahamas', 'Bahrein', 'Bangladesh', 'Barbados', 'Bélgica', 'Belice', 'Benin', 'Bermudas', 'Bielorrusia',
        'Birmania', 'Bolivia', 'Bosnia y Herzegovina', 'Botsuana', 'Brasil', 'Brunei', 'Bulgaria', 'Burkina Faso',
        'Burundi', 'Bután', 'Cabo Verde', 'Camboya', 'Camerún', 'Canadá', 'Catar', 'Chad', 'Chile', 'China',
        'Chipre', 'Ciudad del Vaticano', 'Colombia', 'Comoras', 'Congo', 'Corea del Norte', 'Corea del Sur',
        'Costa de Marfil', 'Costa Rica', 'Croacia', 'Cuba', 'Curazao', 'Dinamarca', 'Dominica', 'Djibutí',
        'Ecuador', 'Egipto', 'El Salvador', 'Emiratos Árabes Unidos', 'España', 'Estados Unidos', 'Estonia',
        'Etiopía', 'Filipinas', 'Finlandia', 'Fiyi', 'Francia', 'Gabón', 'Gambia', 'Gana', 'Georgia',
        'Gibraltar', 'Grecia', 'Groenlandia', 'Guadalupe', 'Guam', 'Guatemala', 'Guayana Francesa', 'Guyana',
        'Haití', 'Holanda', 'Honduras', 'Hong Kong', 'Hungría', 'India', 'Indonesia', 'Irak', 'Irán',
        'Irlanda', 'Irlanda del Norte', 'Isla de Man', 'Islandia', 'Islas Åland', 'Islas Ascensión',
        'Islas Caimán', 'Islas Canarias', 'Islas Cocos', 'Islas Cook', 'Islas Feroe', 'Islas Hébridas',
        'Islas Malvinas', 'Islas Marianas', 'Islas Norfolk', 'Islas Palau', 'Islas Pitcairn', 'Islas Salomón',
        'Islas Seychelles', 'Islas Turks y Caicos', 'Islas Vírgenes Británicas', 'Islas Vírgenes de EE. UU.',
        'Italia', 'Jamaica', 'Japón', 'Jersey', 'Jordania', 'Kazajistán', 'Kenia', 'Kirguistán', 'Kiribati',
        'Kuwait', 'Laos', 'Lesoto', 'Letonia', 'Líbano', 'Liberia', 'Libia', 'Liechtenstein', 'Lituania',
        'Luxemburgo', 'Macao', 'Macedonia del Norte', 'Madagascar', 'Malasia', 'Malawi', 'Maldivas', 'Mali',
        'Malta', 'Marruecos', 'Martinica', 'Mauricio', 'Mauritania', 'Mayotte', 'México', 'Micronesia',
        'Moldavia', 'Mónaco', 'Mongolia', 'Montenegro', 'Montserrat', 'Mozambique', 'Namibia', 'Nauru',
        'Nepal', 'Nicaragua', 'Níger', 'Nigeria', 'Niue', 'Noruega', 'Nueva Caledonia', 'Nueva Zelanda',
        'Omán', 'Países Bajos', 'Panamá', 'Papúa Nueva Guinea', 'Paquistán', 'Paraguay', 'Perú',
        'Polinesia Francesa', 'Polonia', 'Puerto Rico', 'Qatar', 'República Centroafricana', 'República Checa',
        'República Democrática del Congo', 'República Dominicana', 'Reunión', 'Ruanda', 'Rumania', 'Rusia',
        'Saba', 'Sahara Occidental', 'Samoa', 'Samoa Americana', 'San Bartolomé', 'San Cristóbal y Nieves',
        'San Eustaquio', 'San Marino', 'San Martín', 'San Pedro y Miquelón', 'San Vicente y las Granadinas',
        'Santa Elena', 'Santa Lucía', 'Santo Tomé y Príncipe', 'Senegal', 'Serbia', 'Seychelles',
        'Sierra Leona', 'Singapur', 'Sint Maarten', 'Siria', 'Somalia', 'Sri Lanka', 'Suazilandia',
        'Sudáfrica', 'Sudán', 'Sudán del Sur', 'Suecia', 'Suiza', 'Surinam', 'Svalbard y Jan Mayen',
        'Tailandia', 'Taiwán', 'Tanzania', 'Tayikistán', 'Territorio Británico del Océano Índico',
        'Terranova y Labrador', 'Territorios Franceses del Sur', 'Timor Oriental', 'Togo', 'Tokelau',
        'Tonga', 'Trinidad y Tobago', 'Túnez', 'Turkmenistán', 'Turquía', 'Turks y Caicos', 'Tuvalu',
        'Ucrania', 'Uganda', 'Uruguay', 'Uzbekistán', 'Vanuatu', 'Venezuela', 'Vietnam', 'Wallis y Futuna',
        'Yemen', 'Zambia', 'Zimbabue'
    ];
}
